org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=bannerpoint
mod.name=Bannerpoint
mod.group=me.pajic
mod.version=1.1.1
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Turn banners into locator bar waypoints
mod.sources_url=https://github.com/pajicadvance/bannerpoint
mod.homepage_url=https://modrinth.com/mod/bannerpoint
mod.issues_url=https://github.com/pajicadvance/bannerpoint/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=IfTBNyjQ
publish.curseforge=1540780
publish.github=false
